describe('dataTable component test', function() {
     var component = null;
    var table = {
        'name': 'Scattergram-table',
          'selectable': true,
          'custom-filter-column': { column: 'ib1270', type: 'contains' },
        'second-sort': 'ib1270',
          'column-control': true,
          'id_column': 0,
          'id_column_name': 'ib1270',
          'input-left-table': true
    };

    var result = {
        'insightDescription': 'test_2122',
      'insightID': '12885161449400169231',
      'refQuestion': 'Responsiveness To Ads Across Media Segments',
      'refResponse': 'Ad Adverse',
      'settings': {'timeFormat': 'h:mm tt', 'utcOffset': 3, 'dateFormat': 'MM/dd/yyyy', 'timeZoneId': 'Central Standard Time'},
        'rows': [
        {
            'clusterName': 'Productive Havens',
            'referencePercent': 0.00392305,
            'groupName': null,
            'index1': 540,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 69,
            'chartIndex1': 475,
            'netWorth': '<$250K',
            'income': 'Lowest',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Out & About',
            'referencePercent': 0.00487852,
            'groupName': null,
            'index1': 500,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 30,
            'chartIndex1': 475,
            'netWorth': '$25K-$499K',
            'income': 'Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '24-29',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Outdoor Fervor',
            'referencePercent': 0.00564915,
            'groupName': null,
            'index1': 432,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 58,
            'chartIndex1': 432,
            'netWorth': '<$10K',
            'income': 'Low Middle',
            'urbanicity': 'Rural',
            'age': '18-29',
            'index2': 100,
            'homeOwnership': 'Renter/Owner'
        },
        {
            'clusterName': 'Creative Variety',
            'referencePercent': 0.00536224,
            'groupName': null,
            'index1': 410,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 42,
            'chartIndex1': 410,
            'netWorth': '<$500K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '24-35',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Staying Healthy',
            'referencePercent': 0.0037949,
            'groupName': null,
            'index1': 316,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 68,
            'chartIndex1': 316,
            'netWorth': '<$999K',
            'income': 'Lowest',
            'urbanicity': 'Downtown Metro',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Working & Active',
            'referencePercent': 0.00441084,
            'groupName': null,
            'index1': 299,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 35,
            'chartIndex1': 299,
            'netWorth': '<$500K',
            'income': 'Middle',
            'urbanicity': 'City & Surrounds',
            'age': '36-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'City Mixers',
            'referencePercent': 0.0053651,
            'groupName': null,
            'index1': 290,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 29,
            'chartIndex1': 290,
            'netWorth': '<$999K',
            'income': 'Upper Middle',
            'urbanicity': 'Downtown Metro',
            'age': '36-45',
            'index2': 100,
            'homeOwnership': 'Owner/Renter'
        },
        {
            'clusterName': 'Work & Outdoors',
            'referencePercent': 0.0056754,
            'groupName': null,
            'index1': 274,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 54,
            'chartIndex1': 274,
            'netWorth': '$10K-$999K',
            'income': 'Low Middle',
            'urbanicity': 'Rural',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Work & Causes',
            'referencePercent': 0.00715133,
            'groupName': null,
            'index1': 262,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 43,
            'chartIndex1': 262,
            'netWorth': '$10K-$499K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '46-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'First Steps',
            'referencePercent': 0.00909352,
            'groupName': null,
            'index1': 228,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 67,
            'chartIndex1': 228,
            'netWorth': '<$5K',
            'income': 'Lowest',
            'urbanicity': 'City & Surrounds',
            'age': '24-29',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'City Life',
            'referencePercent': 0.01215742,
            'groupName': null,
            'index1': 207,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 61,
            'chartIndex1': 207,
            'netWorth': '<$10K',
            'income': 'Low Middle',
            'urbanicity': 'Downtown Metro',
            'age': '24-35',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Outward Bound',
            'referencePercent': 0.01098423,
            'groupName': null,
            'index1': 200,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 34,
            'chartIndex1': 200,
            'netWorth': '<$250K',
            'income': 'Middle',
            'urbanicity': 'Rural',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Rural Adventure',
            'referencePercent': 0.0076641,
            'groupName': null,
            'index1': 198,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 41,
            'chartIndex1': 198,
            'netWorth': '<$100K',
            'income': 'Middle',
            'urbanicity': 'Rural',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner/Renter'
        },
        {
            'clusterName': 'Country Enthusiasts',
            'referencePercent': 0.00566257,
            'groupName': null,
            'index1': 197,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 16,
            'chartIndex1': 197,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Rural',
            'age': '36-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Rural Parents',
            'referencePercent': 0.00942142,
            'groupName': null,
            'index1': 195,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 47,
            'chartIndex1': 195,
            'netWorth': '<$250K',
            'income': 'Middle',
            'urbanicity': 'Rural',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner/Renter'
        },
        {
            'clusterName': 'Hobbies & Shopping',
            'referencePercent': 0.01065814,
            'groupName': null,
            'index1': 195,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 65,
            'chartIndex1': 195,
            'netWorth': '<$250K',
            'income': 'Lowest',
            'urbanicity': 'Suburbs & Towns',
            'age': '66-75',
            'index2': 100,
            'homeOwnership': 'Owner/Renter'
        },
        {
            'clusterName': 'Metro Mix',
            'referencePercent': 0.00555499,
            'groupName': null,
            'index1': 187,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 32,
            'chartIndex1': 187,
            'netWorth': '$100K-$999K',
            'income': 'Middle',
            'urbanicity': 'Downtown Metro',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Setting Goals',
            'referencePercent': 0.01172,
            'groupName': null,
            'index1': 184,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 39,
            'chartIndex1': 184,
            'netWorth': '<$50K',
            'income': 'Low',
            'urbanicity': 'City & Surrounds',
            'age': '18-29',
            'index2': 100,
            'homeOwnership': 'Renter/Owner'
        },
        {
            'clusterName': 'Rural & Active',
            'referencePercent': 0.01320623,
            'groupName': null,
            'index1': 181,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 46,
            'chartIndex1': 181,
            'netWorth': '<$500K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Favorably Frugal',
            'referencePercent': 0.00772693,
            'groupName': null,
            'index1': 181,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 70,
            'chartIndex1': 181,
            'netWorth': '<$5K',
            'income': 'Lowest',
            'urbanicity': 'City & Surrounds',
            'age': '36-45',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Metro Active',
            'referencePercent': 0.00370086,
            'groupName': null,
            'index1': 162,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 56,
            'chartIndex1': 162,
            'netWorth': '<$500K',
            'income': 'Low',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'On the Go',
            'referencePercent': 0.01648648,
            'groupName': null,
            'index1': 152,
            'groupCode': null,
            'kids': 'Kids: Toddler/Preschool',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 12,
            'chartIndex1': 152,
            'netWorth': '$5K-$499K',
            'income': 'Affluent',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Schools & Shopping',
            'referencePercent': 0.00922996,
            'groupName': null,
            'index1': 151,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 11,
            'chartIndex1': 151,
            'netWorth': '$50K-$499K',
            'income': 'Affluent',
            'urbanicity': 'Suburbs & Towns',
            'age': '36-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Firm Foundations',
            'referencePercent': 0.01471798,
            'groupName': null,
            'index1': 149,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 37,
            'chartIndex1': 149,
            'netWorth': '<$500K',
            'income': 'Middle',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Open Houses',
            'referencePercent': 0.00645388,
            'groupName': null,
            'index1': 148,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 44,
            'chartIndex1': 148,
            'netWorth': '$10K-$999K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '56-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Farm & Home',
            'referencePercent': 0.01206299,
            'groupName': null,
            'index1': 145,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 48,
            'chartIndex1': 145,
            'netWorth': '<$250K',
            'income': 'Low Middle',
            'urbanicity': 'Rural',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Career Centered',
            'referencePercent': 0.01707446,
            'groupName': null,
            'index1': 142,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 14,
            'chartIndex1': 142,
            'netWorth': '$25K-$499K',
            'income': 'Affluent',
            'urbanicity': 'City & Surrounds',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Mobile Mixers',
            'referencePercent': 0.01596805,
            'groupName': null,
            'index1': 140,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 59,
            'chartIndex1': 140,
            'netWorth': '<$5K',
            'income': 'Low',
            'urbanicity': 'City & Surrounds',
            'age': '30-35',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Carving Out Time',
            'referencePercent': 0.01198662,
            'groupName': null,
            'index1': 133,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 20,
            'chartIndex1': 133,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '36-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Tenured Proprietors',
            'referencePercent': 0.01456379,
            'groupName': null,
            'index1': 120,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 27,
            'chartIndex1': 120,
            'netWorth': '$5K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Country Ways',
            'referencePercent': 0.01843889,
            'groupName': null,
            'index1': 112,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 15,
            'chartIndex1': 112,
            'netWorth': '$25K-$999K',
            'income': 'Affluent',
            'urbanicity': 'Rural',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Stylish & Striving',
            'referencePercent': 0.01517339,
            'groupName': null,
            'index1': 110,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 52,
            'chartIndex1': 110,
            'netWorth': '<$5K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '36-45',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Role Models',
            'referencePercent': 0.01096231,
            'groupName': null,
            'index1': 105,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 51,
            'chartIndex1': 105,
            'netWorth': '<$500K',
            'income': 'Low Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '66-75',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Comfortable Cornerstones',
            'referencePercent': 0.02020161,
            'groupName': null,
            'index1': 104,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 22,
            'chartIndex1': 104,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '46-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Community Pillars',
            'referencePercent': 0.01860336,
            'groupName': null,
            'index1': 103,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 28,
            'chartIndex1': 103,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'City & Surrounds',
            'age': '76+',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Corporate Connected',
            'referencePercent': 0.02068284,
            'groupName': null,
            'index1': 102,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 3,
            'chartIndex1': 102,
            'netWorth': '$1MM-$2MM',
            'income': 'Wealthy',
            'urbanicity': 'City & Surrounds',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Children First',
            'referencePercent': 0.01179489,
            'groupName': null,
            'index1': 101,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Strengths',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 21,
            'chartIndex1': 101,
            'netWorth': '<$500K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '18-29',
            'index2': 100,
            'homeOwnership': 'Owner/Renter'
        },
        {
            'clusterName': 'Casual Comfort',
            'referencePercent': 0.00979698,
            'groupName': null,
            'index1': 98,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 6,
            'chartIndex1': 98,
            'netWorth': '$100K-$499K',
            'income': 'Wealthy',
            'urbanicity': 'Suburbs & Towns',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Community Life',
            'referencePercent': 0.01925343,
            'groupName': null,
            'index1': 97,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 55,
            'chartIndex1': 97,
            'netWorth': '<$500K',
            'income': 'Low',
            'urbanicity': 'Suburbs & Towns',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Home & Garden',
            'referencePercent': 0.01527705,
            'groupName': null,
            'index1': 94,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 49,
            'chartIndex1': 94,
            'netWorth': '$10K-$499K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '76+',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Metro Strivers',
            'referencePercent': 0.01964937,
            'groupName': null,
            'index1': 93,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 53,
            'chartIndex1': 93,
            'netWorth': '<$500K',
            'income': 'Low Middle',
            'urbanicity': 'Downtown Metro',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Offices & Entertainment',
            'referencePercent': 0.0108034,
            'groupName': null,
            'index1': 92,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 45,
            'chartIndex1': 92,
            'netWorth': '<$5K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '24-29',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Good Neighbors',
            'referencePercent': 0.01628827,
            'groupName': null,
            'index1': 90,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 23,
            'chartIndex1': 90,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '56-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Urban Diversity',
            'referencePercent': 0.01985577,
            'groupName': null,
            'index1': 90,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 33,
            'chartIndex1': 90,
            'netWorth': '<$100K',
            'income': 'Middle',
            'urbanicity': 'Downtown Metro',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Careers & Travel',
            'referencePercent': 0.00753917,
            'groupName': null,
            'index1': 90,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 10,
            'chartIndex1': 90,
            'netWorth': '$50K-$499K',
            'income': 'Affluent',
            'urbanicity': 'Suburbs & Towns',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Career Building',
            'referencePercent': 0.01574012,
            'groupName': null,
            'index1': 88,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 24,
            'chartIndex1': 88,
            'netWorth': '<$100K',
            'income': 'Upper Middle',
            'urbanicity': 'City & Surrounds',
            'age': '24-29',
            'index2': 100,
            'homeOwnership': 'Renter/Owner'
        },
        {
            'clusterName': 'Climbing the Ladder',
            'referencePercent': 0.00641829,
            'groupName': null,
            'index1': 87,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 18,
            'chartIndex1': 87,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '30-35',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Occupational Mix',
            'referencePercent': 0.02076706,
            'groupName': null,
            'index1': 84,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 38,
            'chartIndex1': 84,
            'netWorth': '<$500K',
            'income': 'Low Middle',
            'urbanicity': 'City & Surrounds',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Solid Surroundings',
            'referencePercent': 0.01866417,
            'groupName': null,
            'index1': 77,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 8,
            'chartIndex1': 77,
            'netWorth': '$500K-$999K',
            'income': 'Affluent',
            'urbanicity': 'Suburbs & Towns',
            'age': '56-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Practical & Careful',
            'referencePercent': 0.01688086,
            'groupName': null,
            'index1': 75,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 64,
            'chartIndex1': 75,
            'netWorth': '<$100K',
            'income': 'Low',
            'urbanicity': 'Rural',
            'age': '66+',
            'index2': 100,
            'homeOwnership': 'Renter/Owner'
        },
        {
            'clusterName': 'Collegiate Crowd',
            'referencePercent': 0.01703267,
            'groupName': null,
            'index1': 75,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 57,
            'chartIndex1': 75,
            'netWorth': '<$10K',
            'income': 'Middle',
            'urbanicity': 'City & Surrounds',
            'age': '18-23',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Rural & Mobile',
            'referencePercent': 0.01056843,
            'groupName': null,
            'index1': 71,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 60,
            'chartIndex1': 71,
            'netWorth': '<$25K',
            'income': 'Low Middle',
            'urbanicity': 'Rural',
            'age': '30-55',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Movies & Sports',
            'referencePercent': 0.0191761,
            'groupName': null,
            'index1': 70,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 62,
            'chartIndex1': 70,
            'netWorth': '<$5K',
            'income': 'Low',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Getting Established',
            'referencePercent': 0.02490454,
            'groupName': null,
            'index1': 69,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 26,
            'chartIndex1': 69,
            'netWorth': '<$500K',
            'income': 'Upper Middle',
            'urbanicity': 'City & Surrounds',
            'age': '30-45',
            'index2': 100,
            'homeOwnership': 'Renter/Owner'
        },
        {
            'clusterName': 'Persistent & Productive',
            'referencePercent': 0.02785645,
            'groupName': null,
            'index1': 57,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 36,
            'chartIndex1': 57,
            'netWorth': '$10K-$999K',
            'income': 'Middle',
            'urbanicity': 'City & Surrounds',
            'age': '66+',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Great Outdoors',
            'referencePercent': 0.0122877,
            'groupName': null,
            'index1': 55,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 40,
            'chartIndex1': 55,
            'netWorth': '$10K-$999K',
            'income': 'Low Middle',
            'urbanicity': 'Rural',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Staying Home',
            'referencePercent': 0.01431715,
            'groupName': null,
            'index1': 53,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 63,
            'chartIndex1': 53,
            'netWorth': '<$10K',
            'income': 'Low',
            'urbanicity': 'Downtown Metro',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Renter'
        },
        {
            'clusterName': 'Established Elite',
            'referencePercent': 0.0310715,
            'groupName': null,
            'index1': 52,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 2,
            'chartIndex1': 52,
            'netWorth': '$2MM+',
            'income': 'Wealthy',
            'urbanicity': 'City & Surrounds',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Firmly Established',
            'referencePercent': 0.04187522,
            'groupName': null,
            'index1': 46,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 17,
            'chartIndex1': 46,
            'netWorth': '$25K-$999K',
            'income': 'Upper Middle',
            'urbanicity': 'City & Surrounds',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Active Lifestyles',
            'referencePercent': 0.03094358,
            'groupName': null,
            'index1': 28,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 7,
            'chartIndex1': 28,
            'netWorth': '$100K-$499K',
            'income': 'Wealthy',
            'urbanicity': 'Suburbs & Towns',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Top Professionals',
            'referencePercent': 0.01303163,
            'groupName': null,
            'index1': 27,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 4,
            'chartIndex1': 27,
            'netWorth': '$1MM-$2MM',
            'income': 'Wealthy',
            'urbanicity': 'Suburbs & Towns',
            'age': '36-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Active & Involved',
            'referencePercent': 0.02489275,
            'groupName': null,
            'index1': 24,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 5,
            'chartIndex1': 24,
            'netWorth': '$100K-$999K',
            'income': 'Wealthy',
            'urbanicity': 'Suburbs & Towns',
            'age': '46-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Busy Schedules',
            'referencePercent': 0.0240414,
            'groupName': null,
            'index1': 23,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 9,
            'chartIndex1': 23,
            'netWorth': '$500K-$999K',
            'income': 'Upper Middle',
            'urbanicity': 'City & Surrounds',
            'age': '66+',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Summit Estates',
            'referencePercent': 0.01385335,
            'groupName': null,
            'index1': 20,
            'groupCode': null,
            'kids': 'Kids: School-age',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 1,
            'chartIndex1': 20,
            'netWorth': '$2MM+',
            'income': 'Wealthy',
            'urbanicity': 'City & Surrounds',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Country Comfort',
            'referencePercent': 0.01858473,
            'groupName': null,
            'index1': 15,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 19,
            'chartIndex1': 15,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Rural',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Rural Community',
            'referencePercent': 0.02156731,
            'groupName': null,
            'index1': 12,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 50,
            'chartIndex1': 12,
            'netWorth': '$10K-$999K',
            'income': 'Low Middle',
            'urbanicity': 'Rural',
            'age': '66+',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Work & Play',
            'referencePercent': 0.02873073,
            'groupName': null,
            'index1': 12,
            'groupCode': null,
            'kids': 'Kids: Age Mix',
            'maritalStatus': 'Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 13,
            'chartIndex1': 12,
            'netWorth': '$25K-$499K',
            'income': 'Affluent',
            'urbanicity': 'City & Surrounds',
            'age': '36-55',
            'index2': 100,
            'homeOwnership': 'Owner/Renter'
        },
        {
            'clusterName': 'Helping Hands',
            'referencePercent': 0.00979577,
            'groupName': null,
            'index1': 8,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Single/Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 66,
            'chartIndex1': 8,
            'netWorth': '<$500K',
            'income': 'Lowest',
            'urbanicity': 'Downtown Metro',
            'age': '76+',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Clubs & Causes',
            'referencePercent': 0.01961129,
            'groupName': null,
            'index1': 8,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married/Single',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 25,
            'chartIndex1': 8,
            'netWorth': '$25K-$499K',
            'income': 'Upper Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '66-75',
            'index2': 100,
            'homeOwnership': 'Owner'
        },
        {
            'clusterName': 'Mid-Americana',
            'referencePercent': 0.01076132,
            'groupName': null,
            'index1': 0,
            'groupCode': null,
            'kids': 'No Kids',
            'maritalStatus': 'Married',
            'quadrant': 'Opportunities',
            'ageText': null,
            'chartIndex2': 100,
            'ib1270': 31,
            'chartIndex1': 0,
            'netWorth': '$25K-$999K',
            'income': 'Middle',
            'urbanicity': 'Suburbs & Towns',
            'age': '46-65',
            'index2': 100,
            'homeOwnership': 'Owner'
        }
    ]
    };


    beforeEach(function() {
        component = new DataTableComponent('widget-content');
        component.setOptions(table);
        component.setData(result);
        component.draw();
    });

    afterEach(function() {
        button = null;
        $('#widget-content').empty().html('');
    });


    it('check tables', function() {
        waits(500);
        runs(function() {
            var data = component.getData();
            expect(data.info.insightDescription).toEqual('test_2122');
            expect($('#widget-content table').length).toEqual(4);
        });
    });
});

describe('dataTableComponent test', function() {
    var config_ = {
        'name': 'insight-table',
        'json-url': 'srv/Insights/InsightList',
        'top': 20,
        'selectable': true,
        'column-control': true,
        'id_column': 0,
        'id_column_name': 'id',
        'isObjectSelect': true,
        'pagination': true,
        'column-filters': [
            { 'column-index': 1, 'type': 'select', 'name': 'insight-select-filter',
                'component-settings': {
                    'name': 'insight-source-dropdown-filter',
                    'json-data': [
                        { 'val': 'IL', 'text': 'Analytic Dataset' },
                        { 'val': 'AM', 'text': 'Audience Manager' }],
                    'defaultValue': 'Select a Source'
                }
            }, {
                'column-index': 4,
                'type': 'date-range',
                'name': 'insight-date-range',
                'range-selector': {
                    'name': 'insight-date-range-selector',
                    'control': 'dropdown',
                    'json-data': [
                        { 'val': '', 'text': 'All', 'default': true, 'disabled': true },
                        { 'val': '30', 'text': 'Previous 30'},
                        { 'val': '60', 'text': 'Previous 60'},
                        { 'val': '90', 'text': 'Previous 90'},
                        { 'val': '365', 'text': 'Previous Year'}],
                    'css-class': '',
                    'defaultValue': 'Select Date Range'
                }

            }, { 'column-index': 7, 'type': 'number-range', 'name': 'insight-number-range' },
            { 'column-index': 3, 'type': 'user-select', 'name': 'insight-user-select', 'component-settings': { 'name': 'insight-user-dropdown-filter',
                'json-data': [],
                'defaultValue': 'Created by'
            }
            }],
        'drawerMenu': [{
            'href': 'personicx/index.html#unique_param/portrait',
            'title': 'Personicx',
            'img_srv': '../resources/img/psx_report_drawer_image.png'
        },
            {
                'href': 'dpa/index.html#unique_param',
                'title': 'Portrait',
                'img_srv': '../resources/img/portrait_report_drawer_image.png'
            },
            {
                'href': 'dpa/index.html#unique_param/audience',
                'title': 'Propensities',
                'img_srv': '../resources/img/audience_report_drawer_image.png'
            }
        ],
        'update-status' : {
            statusArray: ['INSIGHT_COMPLETED', 'INSIGHT_FAILED_TO_INITIATE_ENHANCEMENT', 'INSIGHT_FAILED_DURING_ENHANCEMENT', 'INSIGHT_FAILED_DURING_VERIFICATION'],
            'status-url': 'srv/notificationService/InsightStatusList',
            'columns': [{
                'table-prop': 'recordCount',
                'srv-prop': 'recordCount'
            },
                {
                    'table-prop': 'status',
                    'srv-prop': 'status'
                }],
            'id-prop': 'insightID',
            'query-param': 'insightid',
            'callback': function(value) {
                var currentRow = $('input[value=' + value['insightID'] + ']').closest('tr');
                if (currentRow.next().hasClass('info')) {
                    currentRow.find('td:eq(1)').click();
                    currentRow.find('td:eq(1)').click();
                }
            }
        }
    };
    var dataTable;
    var dataLoader = new DataLoader();
    var options = {
        'name': 'myModelsTable',
        'json-url': '/modelingService/getModelList',
        'top': 20,
        'selectable': true,
        'column-control': false,
        'pagination': false,
        'totals': false,
        'myModelParams': true,
        'choosen': true,
        'isObjectSelect': true,
        'link': {
            'column_number': 1,
            'href': 'scorecards'
        },
        'tableColumns': ['id', 'Description', 'InsightDescription', 'Status', 'CreatedDate'],
        'search': { 'source': 'C' },
        'id_column_name': 'id',
        'uncheck-all': 1,
        'mymodels-status-url': 'srv/notificationService/ModelStatusList'
    };

    // var mapping_ = new ApiMapping;
    //  options['columns'] = mapping_.getMapping(options['tableColumns']);

    beforeEach(function() {
        dataLoader.loadData(options['json-url'], function(result) {
            var container = document.getElementById('widget-content');
            dataTable = new DataTableComponent(container);
            dataTable.setOptions(options);
            dataTable.setData(result['rows']);
            dataTable.draw();
            dataTable.redrawTable();
            dataTable.uncheckAll();
            dataTable.groupTable('insightDescription');
        });
    });

    afterEach(function() {
        dataTable = null;
        $('#widget-content').empty().html('');
    });

    it('check dataTable', function() {
        expect($('#widget-content body')).toBeTruthy();
    });

    xit('check sorting', function() {
        waits(500);
        runs(function() {
            expect($('#widget-content tbody tr:eq(0) td:eq(2)').text()).toEqual('cxcxcxc');
            $('#widget-content thead th:eq(2)').click();
            expect($('#widget-content tbody tr:eq(0) td:eq(2)').text()).toEqual('Testst');
        });
    });

    xit('check getData', function() {
        waits(500);
        runs(function() {
            $('#widget-content tbody input:eq(2)').click();
            var data = dataTable.getData();
            expect(data['sObjects'][0]['description']).toEqual($('#widget-content tbody tr:eq(2) td:eq(2)').text());
        });
    });

    it('Analytic Dataset table test', function() {
        /**@type {Object}*/
        var options = {
            'name': config_['name'],
            'drawerMenu': config_['drawerMenu'],
            'id_column_name': config_['id_column_name'],
            'isObjectSelect': config_['isObjectSelect'],
            'server-side-processing': true,
            'column-filters': config_['column-filters'],
            'update-status': config_['update-status'],
            'use-column-filters': true,
            'tableoptions': {
                'sAjaxSource': config_['json-url'],
                'oLanguage': {
                    'sSearch': '',
                    'sZeroRecords': "<a style='display: block' href='#'>Click here to create an Analytic Dataset</a>"
                }
            }
        };
        options['tableoptions']['bPaginate'] = options['tableoptions']['bServerSide'] = true;
        /** @type {Node|Element|undefined} */
        var div = document.getElementById('widget-content').appendChild(document.createElement('DIV'));
        div.className = 'widget-container acxiom-datatable acxiom-datatable-inslist';
        div.innerHTML = '';
        dataTable = /*component ||*/new DataTableComponent(div);
        dataTable.WIDGET_NAME = config_['name'];
        dataTable.JSON_URI = config_['sAjaxSource'];
        dataTable.initWidget(options);
        dataTable.holderTable();
    });
});
